### PR TITLE
Fix German translations

### PR DESCRIPTION
**Pull request by Synchunk**
There were a few problems with the German translations, and a few English words that weren't translated.
I also replaced a very uncommon word in `loc/de/sets.txt`.

**Note**: The actual reason I started translating this was because of the translation `Sorry, es gibt keine weiteren Informationen im Moment` (English: `Sorry, there is no further information at the moment.`).
I wanted to change that to `Entschuldigung, es gibt zurzeit keine weiteren Informationen` due to a grammatical error but I wasn't able to find the translation anywhere in this repository.

### CODE REVIEW

**Comment by vasa-c** [comment]
Synchunk, thank you!

**Comment by asanov** [comment]
Sorry, there was an out-of-date file interface.txt in the repository. Сheck it please now.

**Comment by Synchunk** [comment]
@asanov weird, I still can't find it :worried:

**Comment by vasa-c** [comment]
Synchunk, https://github.com/unicode-table/unicode-table-data/blob/master/loc/de/interface.txt

**Comment by Synchunk** [comment]
Edited my comment. I can't find the line I wanted to change in that file :(

**Comment by asanov** [comment]
This line now calls "content-sorry"

**Comment by asanov** [comment]
@vasa-c says it's always calls "content-sorry" :)

**Comment by Synchunk** [comment]
I didn't see that as I was searching for the old translation, sorry!
The new translation is way better, but you *could* change it to `Es tut uns leid, dieser Text wurde noch nicht verfasst.` or `Es tut uns leid, es gibt zurzeit keine weiteren Informationen.`.
I can create a pull request if you want :smiley:

**Comment by asanov** [comment]
yes please, it would be good

**Comment by Synchunk** [comment]
will do that in a second! :)

**Comment by Synchunk** [comment]
Done, using a slightly different version of what I suggested above! #18

**Pull request merged**
